[phases.setup]
nixPkgs = ["...", "php82Extensions.pdo_mysql", "php82Extensions.mysql"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link --force && vendor/bin/heroku-php-apache2 public/"
