[phases.setup]
nixPkgs = ["...", "php82Extensions.pdo_mysql", "php82Extensions.mysql", "php82Extensions.openssl"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "mkdir -p storage/app/public/profile_photos",
    "mkdir -p bootstrap/cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan storage:link --force 2>&1 && php artisan migrate --force && php artisan queue:work --daemon --tries=3 --timeout=120 & vendor/bin/heroku-php-apache2 public/"
