<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #000;
        }
        .meta-info {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
        }
        .meta-info p {
            margin: 5px 0;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 11px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .action-type {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .action-login { background-color: #d4edda; color: #155724; }
        .action-logout { background-color: #f8f9fa; color: #6c757d; }
        .action-create { background-color: #cce5ff; color: #004085; }
        .action-update { background-color: #fff3cd; color: #856404; }
        .action-delete { background-color: #f8d7da; color: #721c24; }
        .action-view { background-color: #e2e3ff; color: #383d41; }
        .action-export { background-color: #d1ecf1; color: #0c5460; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .ip-address {
            font-family: 'Courier New', monospace;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
    </div>

    <div class="meta-info">
        <p><strong>Generated:</strong> {{ now()->format('d M Y - h:i A') }}</p>
        <p><strong>Total Records:</strong> {{ $logs->count() }}</p>
        @if($logs->count() > 0)
            <p><strong>Date Range:</strong> {{ $logs->min('created_at')->format('d M Y') }} to {{ $logs->max('created_at')->format('d M Y') }}</p>
        @endif
    </div>

    @if($logs->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 8%;">ID</th>
                    <th style="width: 12%;">Action Type</th>
                    <th style="width: 30%;">Description</th>
                    <th style="width: 15%;">Date & Time</th>
                    <th style="width: 10%;">IP Address</th>
                    <th style="width: 15%;">User Name</th>
                    <th style="width: 10%;">Time Ago</th>
                </tr>
            </thead>
            <tbody>
                @foreach($logs as $log)
                    <tr>
                        <td>#{{ $log->id }}</td>
                        <td>
                            <span class="action-type action-{{ $log->action_type }}">
                                {{ ucfirst($log->action_type) }}
                            </span>
                        </td>
                        <td>{{ $log->description }}</td>
                        <td>{{ $log->formatted_date }}</td>
                        <td class="ip-address">{{ $log->ip_address }}</td>
                        <td>
                            @if($log->user)
                                {{ $log->user->name }}<br>
                                <small style="color: #666;">{{ $log->user->email }}</small>
                            @else
                                <em style="color: #999;">Unknown User</em>
                            @endif
                        </td>
                        <td>{{ $log->time_elapsed }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #666;">
            <p style="font-size: 18px;">No activity logs found</p>
            <p>No records match the current criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>Activity Logs Report - Generated by Employee Self Service System</p>
        <p>{{ now()->format('Y-m-d H:i:s T') }}</p>
    </div>
</body>
</html>